export const PROXY_LIST_LOADING = 'PROXY_LIST_LOADING';
export const PROXY_LIST_SUCCESS = 'PROXY_LIST_SUCCESS';
export const PROXY_LIST_ERROR = 'PROXY_LIST_ERROR';

export const PROXY_CREATE_REQUEST = 'PROXY_CREATE_REQUEST';
export const PROXY_CREATE_SUCCESS = 'PROXY_CREATE_SUCCESS';
export const PROXY_CREATE_ERROR = 'PROXY_CREATE_ERROR';

export const PROXY_UPDATE_REQUEST = 'PROXY_UPDATE_REQUEST';
export const PROXY_UPDATE_SUCCESS = 'PROXY_UPDATE_SUCCESS';
export const PROXY_UPDATE_ERROR = 'PROXY_UPDATE_ERROR';

export const PROXY_DELETE_REQUEST = 'PROXY_DELETE_REQUEST';
export const PROXY_DELETE_SUCCESS = 'PROXY_DELETE_SUCCESS';
export const PROXY_DELETE_ERROR = 'PROXY_DELETE_ERROR';
