export const SETTING_LIST_LOADING = 'SETTING_LIST_LOADING';
export const SETTING_LIST_SUCCESS = 'SETTING_LIST_SUCCESS';
export const SETTING_LIST_ERROR = 'SETTING_LIST_ERROR';

export const SETTING_UPDATE_REQUEST = 'SETTING_UPDATE_REQUEST';
export const SETTING_UPDATE_SUCCESS = 'SETTING_UPDATE_SUCCESS';
export const SETTING_UPDATE_ERROR = 'SETTING_UPDATE_ERROR';

